# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('setup_guide', '0002_auto_20180207_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='sub_heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='sub_heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='sub_heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='sub_heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidelandingpage',
            name='sub_heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='sub_heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='sub_heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='sub_heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='sub_heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='sub_heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='subsections_de',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='subsections_en',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='subsections_es',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='subsections_fr',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='setupguidepage',
            name='subsections_pt',
            field=wagtail.core.fields.StreamField((('markdown', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))),), null=True),
        ),
    ]
