# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_branding_language_choice_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='skip_to_main_text',
            field=models.CharField(default='Skip to main content', max_length=40),
        ),
    ]
