# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('invest', '0009_branding_skip_to_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
