# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 09:34
from __future__ import unicode_literals

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactagentemail_contactuseremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)'),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_ar',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_de',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_en',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_es',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_fr',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_ja',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_pt',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactagentemail',
            name='footer_zh_cn',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:'),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_ar',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_de',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_en',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_es',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_fr',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_ja',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_pt',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='body_text_zh_cn',
            field=wagtailmarkdown.fields.MarkdownField(default='\nThank you for contacting the Department for International Trade about your investment plans.\n\nWe have received the information you sent through the Invest in Great Britain website and will aim to follow up with\nyou in the next 7 days. Your enquiry may be forwarded to a local post for follow up.\n\nThe Department for International Trade provides free and impartial advice to companies around the world interested in\ndoing business in the UK. We look forward to welcoming you as one of the many companies to enjoy success in the UK.\nFind our Terms and Conditions [here](http://https://invest.great.gov.uk/int/terms-and-conditions/).\n\nSee below for your submitted form:', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)'),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_ar',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_de',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_en',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_es',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_fr',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_ja',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_pt',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
        migrations.AlterField(
            model_name='contactuseremail',
            name='footer_zh_cn',
            field=wagtailmarkdown.fields.MarkdownField(default='\nDepartment for International Trade (DIT) is the Government Department that helps UK‑based companies succeed in the\nglobal economy. We also help overseas companies bring their high-quality investment to the UK’s dynamic economy,\nacknowledged as Europe’s best place in which to succeed in global business.\n\n[invest.great.gov.uk](http://https://invest.great.gov.uk)', null=True),
        ),
    ]
