# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('contact', '0005_auto_20180430_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSuccessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body_text', wagtailmarkdown.fields.MarkdownField()),
                ('body_text_en', wagtailmarkdown.fields.MarkdownField(null=True)),
                ('body_text_de', wagtailmarkdown.fields.MarkdownField(null=True)),
                ('body_text_es', wagtailmarkdown.fields.MarkdownField(null=True)),
                ('body_text_fr', wagtailmarkdown.fields.MarkdownField(null=True)),
                ('body_text_pt', wagtailmarkdown.fields.MarkdownField(null=True)),
                ('body_text_ar', wagtailmarkdown.fields.MarkdownField(null=True)),
                ('body_text_ja', wagtailmarkdown.fields.MarkdownField(null=True)),
                ('body_text_zh_cn', wagtailmarkdown.fields.MarkdownField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
