# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_how_we_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_de',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_en',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_es',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_fr',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_pt',
            field=wagtail.core.fields.StreamField((('items', wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())))),), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
