# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180327_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text',
            field=models.TextField(default='Search more industries', max_length=255),
        ),
    ]
