# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_sector_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_ar',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_de',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_en',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_es',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_fr',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_ja',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_pt',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sector_button_text_zh_cn',
            field=models.TextField(default='See more industries', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sector_button_text',
            field=models.TextField(default='See more industries', max_length=255),
        ),
    ]
