# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180514_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_pt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='how_we_help_lead_in_zh_cn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
