# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_svgmap.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_auto_20180302_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionlandingpage',
            name='heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionlandingpage',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionlandingpage',
            name='heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionlandingpage',
            name='heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionlandingpage',
            name='heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='heading_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='heading_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='heading_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='heading_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='heading_pt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='subsections_de',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))), ('location', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('info', wagtailmarkdown.blocks.MarkdownBlock()), ('map', wagtail.core.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))), null=True, on_delete=django.db.models.deletion.CASCADE)))))), null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='subsections_en',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))), ('location', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('info', wagtailmarkdown.blocks.MarkdownBlock()), ('map', wagtail.core.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))), null=True, on_delete=django.db.models.deletion.CASCADE)))))), null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='subsections_es',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))), ('location', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('info', wagtailmarkdown.blocks.MarkdownBlock()), ('map', wagtail.core.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))), null=True, on_delete=django.db.models.deletion.CASCADE)))))), null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='subsections_fr',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))), ('location', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('info', wagtailmarkdown.blocks.MarkdownBlock()), ('map', wagtail.core.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))), null=True, on_delete=django.db.models.deletion.CASCADE)))))), null=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='subsections_pt',
            field=wagtail.core.fields.StreamField((('content', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('content', wagtailmarkdown.blocks.MarkdownBlock())))), ('location', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(max_length=255)), ('info', wagtailmarkdown.blocks.MarkdownBlock()), ('map', wagtail.core.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.core.blocks.CharBlock(label='CSS class', required=False))), null=True, on_delete=django.db.models.deletion.CASCADE)))))), null=True),
        ),
    ]
